# Generated by Django 4.0.6 on 2022-08-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenith', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='site_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
