# Generated by Django 4.0.6 on 2022-08-06 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zenith', '0002_remove_image_site_image_remove_student_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='LAUTECH', max_length=100),
            preserve_default=False,
        ),
    ]
