# Generated by Django 4.1.4 on 2023-03-06 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zenith', '0008_alter_message_full_name_paymentfile_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='dp',
        ),
    ]
